# Welcome to Jekyll!
#

# Site settings
title: The First Sip of Tea
still: Inspiring Moments of Stillness
description: |
  
  Fresh ◦ Traditional ◦ Authentic
owner: The Spice Hut # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: charles@thespicehut.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thefirstsipoftea.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github:
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/spicehut/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: info@thespicehut.com
  #flickr:
  instagram: https://www.instagram.com/thespicehut/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  amazon: https://www.amazon.com/thespicehut

# Build settings
markdown: kramdown
#sass:
#  style: compressed
